version: '3'

services:

### ub1nu11 service
  ub1nu11:
    build: .
    container_name: ub1nu11
    restart: always
    ports:
      - "8080:80"
    image: "f0rc3ps/ub1nu11:latest"

### Grafana 
   grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '3000:3000'
